swagger: "2.0"
info:
  description: "This document explains available operations for the FireFly Configurator API."
  version: "1.0"
  title: "FireFly Configurator"
  license:
    name: "For licensing, see the repo on GitHub."
    url: "https://github.com/BrentIO/FireFly_Configurator/"
host: "10.1.1.87"
basePath: "/api"
tags:
- name: "System Health"
  description: "Performs a health check on the HTTP and database servers"
- name: "Circuit Breaker"
  description: "Retrieves, edits, and deletes a circuit breaker"
- name: "Controllers"
  description: "Retrieves, edits, and deletes attributes for a controller"
- name: "Switches"
  description: "Retrieves, edits, and deletes attributes for a switch and switch buttons"
- name: "Inputs"
  description: "Retrieves, edits, and deletes inputs to the controller"
- name: "Outputs"
  description: "Retrieves, edits, and deletes outputs from the controller"
- name: "Actions"
  description: "Retrieves, edits, and deletes actions an Input has on an Output"
schemes:
- "http"
paths:
  /heartbeat:
    get:
      tags:
      - "System Health"
      summary: "Retrieves the status of the web and database servers."
      produces:
      - "application/json"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Heartbeat"
        405:
          description: "Method Not Allowed"
        500:
          description: "Internal Server Error"
        503:
          description: "Service Unavailable"
          schema:
            $ref: "#/definitions/Error"
      security: []
  /breaker:
    get:
      tags:
      - "Circuit Breaker"
      produces:
      - "application/json"
      description: "Retrieves a list of all circuit breakers" 
      operationId: listBreakers
      security: 
        - ApiKeyAuth: [] 
      responses:
        200:
          description: "Success"
          schema:
            type: array
            items:
              $ref: "#/definitions/Breaker"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
        500:
          description: "Internal Server Error"
    post:
      tags:
      - "Circuit Breaker"
      produces:
      - "application/json"
      description: "Creates a new circuit breaker" 
      operationId: createBreaker
      security: 
        - ApiKeyAuth: [] 
      responses:
        200:
          description: "Success"
          schema:
            type: array
            items:
              $ref: "#/definitions/Breaker"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
        500:
          description: "Internal Server Error"
  
  /breaker/{id}:
    get:
      tags:
      - "Circuit Breaker"
      produces:
      - "application/json"
      description: "Retrieves a breaker by ID" 
      operationId: getBreakerById
      security: 
        - ApiKeyAuth: [] 
      parameters:
      - name: "id"
        in: "path"
        description: "ID of the breaker to return"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/Breaker"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
        404:
          description: "Not Found"
        405:
          description: "Method Not Allowed"
        500:
          description: "Internal Server Error"
    post:
      tags:
      - "Circuit Breaker"
      produces:
      - "application/json"
      description: "Creates a new or edits an existing circuit breaker" 
      operationId: editBreaker
      security: 
        - ApiKeyAuth: [] 
      parameters:
      - name: "id"
        in: "path"
        description: "ID of the breaker to return"
        required: true
        type: "integer"
        format: "int32"
      responses:
        200:
          description: "Success"
          schema:
            type: array
            items:
              $ref: "#/definitions/Breaker"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
        404:
          description: "Not Found"
        405:
          description: "Method Not Allowed"
        500:
          description: "Internal Server Error"
 
    
securityDefinitions:
  ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key

definitions:
  Heartbeat:
    type: "object"
    properties:
      time:
        type: "string"
        format: "date-time"
        description: "Current date and time UTC"
      status:
        type: "string"
        description: "Will always return \"ok\" on success"
  Error:
    type: "object"
    properties:
      error:
        type: "string"
        description: "Additional data about the given error"
  Breaker:
    type: "object"
    properties:
      id:
        type: "integer"
        description: "Unique ID of the breaker"
      name:
        type: string
        description: "Unique name of the breaker"
      displayName:
        type: string
        description: "A descriptive display name of the breaker"
      amperage:
        type: integer
        description: "The amperage of the breaker"
  ButtonLEDColor:
    type: object
    properties:
      id:
        type: integer
        description: "Unique ID of the button LED color"
      name:
        type: string
        description: "Unique name of the button LED color"
      displayName:
        type: string
        description: "A descriptive display name of the button LED color"
      hexValue:
        type: string
        description: "The button LED color in hex (#XXXXXX)"
      brightnessMinimum:
        type: integer
        minimum: 0
        maximum: 100
        description: "The minimum brightness this LED can be set"
      brightnessMaximum:
        type: integer
        minimum: 0
        maximum: 100
        description: "The maximum brightness this LED can be set"

